### ISSUE TITLE
Installing additional dependencies

### ISSUE THREAD

**Issue by ms609** [r-hub/rhub2#11]
Hi, this looks like a fantastic package that will be very useful in package development!

I've tried to set it up for one of my packages, which lists a `Suggest`ed package ("TreeDistData") using the `Additional_repositories:` description field.  This causes the default workflow runs to [fail](https://github.com/ms609/TreeDist/actions/runs/6716767454/job/18253505262#step:21:551):

```
  Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Could not solve package dependencies:
  * deps::.: Can't install dependency TreeDistData (> 0.1.0)
  * TreeDistData: Can't find package called TreeDistData.
  * any::sessioninfo: dependency conflict
  * any::rcmdcheck: dependency conflict
```

To some extent this represents an [issue with pak](https://github.com/r-lib/actions/issues/534), but I've found it possible to work around this bug in my existing GHA workflows by installing "TreeDistData" from GitHub.
I'm wondering whether I can configure rhub2 to do the same thing; it's not clear that I can achieve this by editing `rhub.yaml`.  Would it be possible to support an option under the `with:` field to, for example, the `r-hub/rhub2/actions/rhub-check` action?

**Comment by gaborcsardi** [comment]
Yes, we definitely need to improve that. For now, as a workaround I think you can edit `rhub.yaml` to install it manually.

**Comment by gaborcsardi** [comment]
With the new workflow + actions, you can pass `extra-packages` to `rhub-setup-deps` and `Config/needs/check` is also recognized in `DESCRIPTION`.

**Comment by ms609** [comment]
Confirmed working – many thanks indeed for the fix!
