### ISSUE TITLE
Platform macos has disappeared.

### ISSUE THREAD

**Issue by rolfTurner** [r-hub/rhub2#12]
I need to build a Mac OSX binary for  a  user of the deldir package.  But there is no longer   any trace of "macos" when I execute platforms().

Earlier today (NZ time) I thought I saw mention of this problem on github, indicating that  macos builds were suspended  because they were not working,  But I can no longer find anything about this.  There is nothing that I can see in "Issues".

Did I imagine seeing this mention?

Will macos builds come back to life?

**Comment by rolfTurner** [comment]
Whoops.  I did indeed neglect to do that.  That  was stupid.

I  think I have now followed the Setup instructions correctly.  I next did

    git add .github/workflows/rhub.yaml.

and then did

    git push

To my complete frustration I then got the prompt

    Username for 'https://github.com': 

This did not happen before (i.e. before I did the setup procedure).  And of course it will not log me in with my  username and github password.  The system is supposed to use the "Git Credential Manager", is it not?  That's what it seemed to be doing previously. 

Fortunately I had saved my "Personal Access Token" that I had needed to create, yesterday, in a file, and I was able to copy and paste that in, in response to the password prompt.  Mirabile dictu, that seemed to work!!!  I then did the rhub2::rhub_doctor() bit,
which said I was good to go, and then rhub2::rhub_check().  I then found my way (can't actually remember how) to a page where progress seemed to get reported.

After a nerve-wracking wait, where nothing seemed to be happening, it appeared to announce that the job was ("all jobs" were)  completed.  "Success" was indicated at the top of the page. 

But *where* is the binary package that I wanted to build?  Going by previous experience with the rhub package, I might have guessed that it would be found under "Artifacts", but there is nothing under Artifacts.

What do I do now?

**Comment by gaborcsardi** [comment]
You can run `rhub2::rhub_doctor()` to check if everything is set up correctly. 

You can also try `gitcreds::gitcreds_get()` to see if your personal access token is set up.

If you are on Linux, then you may need to set a credential helper, e.g.
```
git config --global credential.helper store
```
and then from R
```
gitcreds::gitcreds_set()
```
to add the token.

**Comment by rolfTurner** [comment]
Where, if anywhere, can I find the macos binary package that I was trying to create?

**Comment by rolfTurner** [comment]
I repeat:  Where, if anywhere, can I find the macos binary package that I was trying to create?  If this is not possible, can you confirm that it is not possible?

**Comment by rolfTurner** [comment]
Why am I not getting a response to the foregoing question?  Is the question just too stupid to contemplate?  If so, I am sorry, but I really don't understand.

Gabor, please answer.

**Comment by rolfTurner** [comment]
Apparently it is not possible to produce a binary package using rhub2.

A friend guided me through a rather complicated  procedure, using "Github Actions".
rather than using rhub2.  The procedure creates a binary that runs under x86_64 architecture.

If one wants a binary that runs under arm64 architecture, then life is much simpler.
It turns out that macOS builder kindly provided by Simon Urbanek

        <https://mac.r-project.org/macbuilder/submit.html>

works just like Win-Builder: it takes a source package, checks it and gives a binary package back.
