### ISSUE TITLE
valgrind for memory leak detection: more documentation

### ISSUE THREAD

**Issue by csteglich** [r-hub/rhub2#13]
Hello, here Christian Steglich from the RSiena package for longitudinal network analysis. I was happy to come across the rhub2 package and would like to thank you for providing this service in the first place! 
For our package https://github.com/snlab-nl/rsiena we recently got a complaint of memory leaks diagnosed by **valgrind** from the CRAN people. As Windows user, I cannot work with valgrind to replicate this locally, so tried it via rhub2. It appears that the valgrind checks do not detect anything wrong, unlike the memchecks run at CRAN. I wonder why. Does this mean that rhub2 doesn't check for memory leaks? If not, could it be made to do that?
Additionally, we do not get the protocol files generated when checking via rhub2. Because these contain additonal detailed information when running the checks via rhub2. Is it possible to get them? Edit: I see that this latter aspect may be what Issue #8 refers to.

**Comment by gaborcsardi** [comment]
I modified our action to always upload the check output as an artifact. If you download the artifact, you'll need to look at the `.Rout` files. There is usually one for tests and another one for examples.

E.g. here is an example: https://github.com/gaborcsardi/rsiena/actions/runs/7863114428

Ideally, a valgrind error would also fail the build, so I'll keep this issue open until that is implemented.

**Comment by gaborcsardi** [comment]
OK, now we fail the build if valgrind reports errors, e.g.:
https://github.com/gaborcsardi/SKFCPD/actions/runs/7915285935/job/21606863483
