### ISSUE TITLE
`clang18` system

### ISSUE THREAD

**Issue by danielinteractive** [r-hub/rhub2#15]
Hi all,

thanks a lot for `rhub2`, looks great!

One feature request that you might already be working on: could we get a `clang18` system that is resembling the additional checks on CRAN (I believe by Prof Ripley) closely? That would be super helpful.

Thanks,
best regards
Daniel

**Comment by PascalKieslich** [comment]
Yes, that would be super helpful for my package, too (and thanks also from my side for rhub2, which has helped me a lot with package testing).

**Comment by danielinteractive** [comment]
This could be helpful: @gowerc spent quite some time this week to spin up [this Docker file](https://github.com/gowerc/cran-images/blob/main/fedora-clang-devel/Dockerfile) producing a clang18 system.

**Comment by gaborcsardi** [comment]
Thanks, that `Dockerfile` might very well be needed in the future, but for now I want with a simpler way using binary compiler packages provided by the LLVM project. They seem to reproduce the issues CRAN found.

Building the container right now: https://github.com/r-hub/containers/actions/runs/7904324193

Once it is deployed I'll add it to the rhub2 packages as well.

**Comment by gaborcsardi** [comment]
All done. Please open an issue here or in the `r-hub/containers` repo if you have any issues.

**Comment by danielinteractive** [comment]
Thanks a lot @gaborcsardi !

**Comment by gaborcsardi** [comment]
It is not fedora, it is ubuntu: https://r-hub.github.io/containers/containers.html#clang18
https://github.com/r-hub/containers/blob/main/containers/clang18/Dockerfile

It doesn't matter much what distro it is.

**Comment by gaborcsardi** [comment]
Yes, I would be very surprised if the difference is not due to different compiler options, or maybe versions. Which version of mmrm was this?

**Comment by danielinteractive** [comment]
Yeah that should have been about that time / version.
