### ISSUE TITLE
Provide UTF-8 locale

### ISSUE THREAD

**Issue by krlmlr** [r-hub/rhub2#22]
I'm not suggesting that this should be the default, just that this is available.

https://github.com/duckdb/duckdb-r/actions/runs/8402600629/job/23012169498#step:6:182

**Comment by gaborcsardi** [comment]
Should be deployed ones this is done: https://github.com/r-hub/containers/actions/runs/8410000821

**Comment by gaborcsardi** [comment]
The arrow build error is probably: https://github.com/apache/arrow/issues/40756

**Comment by krlmlr** [comment]
Thanks for accommodating!
